{% set name = "vermouth" %}
{% set version = "0.9.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/vermouth-{{ version }}.tar.gz
  sha256: 0e1712a680a7e9bf862781a38d948097c07884e9f26e1ddb1d78e7dd943576ac

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python
    - wheel
    - setuptools >=30.3.0
    - pbr
    - pip
  run:
    - python
    - pbr
    - numpy
    - networkx >=2.0,<3.dev0
    - scipy

test:
  imports:
    - vermouth
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/marrink-lab/vermouth-martinize
  summary: 'Describe and apply transformation on molecular structures and topologies'
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
