{% set name = "vermouth" %}
{% set version = "0.10.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/vermouth-{{ version }}.tar.gz
  sha256: 2ff36034e63a43bfe5668fc9be8e45ad44e7301d2ce30abb291033f4e4d687da

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python
    - wheel
    - setuptools >=30.3.0
    - pbr
    - pip
  run:
    - python
    - pbr
    - numpy
    - networkx >=2.0,<3.dev0
    - scipy

test:
  imports:
    - vermouth
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/marrink-lab/vermouth-martinize
  summary: Describe and apply transformation on molecular structures and topologies
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
